Deviation Class Reference
#include <Deviation.h>Inheritance diagram for Deviation::
Public Member Functions
Deviation ()
virtual double calculate (Partition *pAPartition, RelationSDN *pARelation, DataSet *pDataSet)
virtual double calculate (Partition &objPartition1, Partition &objPartition2)
Detailed Description
Author
Gustavo Rodrigues
Since
12/03/10
Version
2.0
Definition at line 25 of file Deviation.h.
Constructor & Destructor Documentation
Deviation::Deviation ()
Does nothing
Parameters
Don't have any parameter
Definition at line 11 of file Deviation.cpp.
Member Function Documentation
double Deviation::calculate (Partition & objPartition1, Partition & objPartition2) [virtual]
Does nothing
Implements ValidationIndex.
Definition at line 40 of file Deviation.cpp.
double Deviation::calculate (Partition * pAPartition, RelationSDN * pARelation, DataSet * pDataSet) [virtual]
Return value of deviation from parameter partition
Parameters
Partition,RelationSDN and DataSet
Returns
Value deviation
calculate the summed distances for each pattern of a cluster
Implements ValidationIndex.
Definition at line 15 of file Deviation.cpp.
References Similarity::calculate(), Partition::getCentroidInCluster(), DataSet::getMapVector(), Partition::getObjectsInCluster(), RelationSDN::getSimilarity(), and Partition::getVectorObjCluster().
The documentation for this class was generated from the following files:
ValidationIndex/Deviation.h
ValidationIndex/Deviation.cpp