DataSet Class Reference
Responsible to manage the dataset file into the memory.
#include <DataSet.h>
Public Member Functions
DataSet ()
DataSet (string sPathADataSet, string sANameDataSet)
map< string, map< string, double > > generateMatrix (Similarity *pAObSimilarity)
void tabulateMappingDataSet ()
int getNumberOfFeature ()
int getNumberOfObjects ()
string getNameDataSet ()
map< string, vector< double > > getMapVector ()
fs::path getPathToDataSet ()
vector< string > getVElements ()
RelationSDN * getRelation (int iAPosRelation)
void addNewRelationSDN (Similarity *pAObSimilarity)
void setNameDataSet (string sANameDataSet)
Public Attributes
vector< Similarity * > vectorObSimilarity
Detailed Description
Responsible to manage the dataset file into the memory.
Author
Valter Henrique, Gustavo Henrique
Since
01/02/10
Version
2.0 Dataset class is responsible to inform the data to MOCLE
Definition at line 40 of file DataSet.h.
Constructor & Destructor Documentation
DataSet::DataSet ()
Does nothing
Parameters
Don't have any parameter
DataSet::DataSet (string sPathADataSet, string sANameDataSet)
Ask to the user what kind format is the dataset then choose a specific method to pass the dataset to memory of the computer
Parameters
the path to the dataset in the computer
Definition at line 10 of file DataSet.cpp.
References tabulateMappingDataSet().
Member Function Documentation
void DataSet::addNewRelationSDN (Similarity * pAObSimilarity)
Add new object RelationSDN in vectorRelations vector
Parameters
Object similarity
Returns
Don't have
Definition at line 40 of file DataSet.cpp.
References generateMatrix(), RelationSDN::setNnList(), RelationSDN::setSimilarity(), and RelationSDN::setSimilarityMatrix().
map< string, map< string, double > > DataSet::generateMatrix (Similarity * pAObSimilarity)
Generate the Distance matrix get in the dataset file to the memory
Parameters
Object similarity
Returns
Matrix map
Definition at line 52 of file DataSet.cpp.
References Similarity::calculate().
Referenced by addNewRelationSDN().
map< string, vector< double > > DataSet::getMapVector ()
Returns the dataset mapped int th struct
Returns
pathToDataSet
Definition at line 131 of file DataSet.cpp.
Referenced by Silhouette::calculate(), and Deviation::calculate().
int DataSet::getNumberOfFeature ()
Returns the number of features existing in dataset
Returns
iNumFeatures
Definition at line 119 of file DataSet.cpp.
int DataSet::getNumberOfObjects ()
Returns the number of objects existing in dataset
Returns
iNumFeatures
Definition at line 123 of file DataSet.cpp.
Referenced by Connectivity::calculate(), and Partition::generateRandomPartition().
RelationSDN * DataSet::getRelation (int iAPosRelation)
Return pointer for vector RelationSDN
Parameters
Position of vector
Returns
RelationSDN*
Definition at line 36 of file DataSet.cpp.
vector< string > DataSet::getVElements ()
Return vector of all objects from dataset
Parameters
Don't have
Returns
vector<string>
Definition at line 32 of file DataSet.cpp.
Referenced by Connectivity::calculate().
void DataSet::setNameDataSet (string sANameDataSet)
Set the name of the dataset file
Parameters
String sANameDataset
Returns
Don't have
Definition at line 135 of file DataSet.cpp.
void DataSet::tabulateMappingDataSet ()
Read the file passed in the argument pathADatSet and allocate in the memory
Parameters
pathADataSet receive the path from the dataset
Definition at line 77 of file DataSet.cpp.
Referenced by DataSet().
The documentation for this class was generated from the following files:
DataSet.h
DataSet.cpp