Silhouette Class Reference
#include <Silhouette.h>Inheritance diagram for Silhouette::
Public Member Functions
virtual double calculate (Partition *pAPartition, RelationSDN *pARelation, DataSet *pADataset)
virtual double calculate (Partition &objPartition1, Partition &objPartition2)
Detailed Description
Author
Gustavo Rodrigues
Since
22/03/10
Version
2.0
Definition at line 22 of file Silhouette.h.
Member Function Documentation
double Silhouette::calculate (Partition & objPartition1, Partition & objPartition2) [virtual]
Does nothing
Implements ValidationIndex.
Definition at line 205 of file Silhouette.cpp.
double Silhouette::calculate (Partition * pAPartition, RelationSDN * pARelation, DataSet * pADataset) [virtual]
Return value of silhouette from parameter partition
Parameters
Partition,RelationSDN and DataSet
Returns
Value silhouette
Implements ValidationIndex.
Definition at line 18 of file Silhouette.cpp.
References Similarity::calculate(), DataSet::getMapVector(), Partition::getObjectsInCluster(), RelationSDN::getSimilarity(), and Partition::getVectorObjCluster().
The documentation for this class was generated from the following files:
ValidationIndex/Silhouette.h
ValidationIndex/Silhouette.cpp