RelationSDN Class Reference
#include <RelationSDN.h>
Public Member Functions
RelationSDN (SimilarityMatrix objASimilarityMatrix, NnList objANnList, Similarity *pAObjSimilarity)
SimilarityMatrix getSimilarityMatrix ()
Similarity * getSimilarity ()
NnList getNnList ()
void setSimilarityMatrix (map< string, map< string, double > > mapObjMap)
void setSimilarity (Similarity *pObjSimilarity)
void setNnList (map< string, map< string, double > > mapObjMap)
Detailed Description
Author
Gustavo Rodrigues
Since
12/03/10
Version
2.0 This class stores an object in which the similarity is generated from this similarity matrix and is created from the list of nearest neighbors.
Definition at line 23 of file RelationSDN.h.
Member Function Documentation
NnList RelationSDN::getNnList ()
Return nearest neighbor list
Parameters
Don't have
Returns
Object NnList
Definition at line 33 of file RelationSDN.cpp.
Referenced by Connectivity::calculate().
Similarity * RelationSDN::getSimilarity ()
Return pointer measure similarity
Parameters
Don't have
Returns
Pointer Similarity
Definition at line 29 of file RelationSDN.cpp.
Referenced by Silhouette::calculate(), and Deviation::calculate().
SimilarityMatrix RelationSDN::getSimilarityMatrix ()
Return object similarity Matrix
Parameters
Don't have
Returns
Similarity Matrix
Definition at line 24 of file RelationSDN.cpp.
void RelationSDN::setNnList (map< string, map< string, double > > mapObjMap)
Set nearest neighbor list
Parameters
Matrix map
Returns
Don't have
Definition at line 45 of file RelationSDN.cpp.
References NnList::setNnList().
Referenced by DataSet::addNewRelationSDN().
void RelationSDN::setSimilarity (Similarity * pObjSimilarity)
Set measure similarity
Parameters
Pointer similarity
Returns
Don't have
Definition at line 41 of file RelationSDN.cpp.
Referenced by DataSet::addNewRelationSDN().
void RelationSDN::setSimilarityMatrix (map< string, map< string, double > > mapObjMap)
Set object Similarity Matrix
Parameters
Matrix map
Returns
Don't have
Definition at line 37 of file RelationSDN.cpp.
References SimilarityMatrix::setMatrix().
Referenced by DataSet::addNewRelationSDN().
The documentation for this class was generated from the following files:
RelationSDN.h
RelationSDN.cpp