Connectivity Class Reference
#include <Connectivity.h>Inheritance diagram for Connectivity::
Public Member Functions
Connectivity (float aSizeNn)
virtual double calculate (Partition *pAPartition, RelationSDN *pARelation, DataSet *pDataSet)
virtual double calculate (Partition &objPartition1, Partition &objPartition2)
Detailed Description
Author
Gustavo Rodrigues
Since
12/03/10
Version
2.0
Definition at line 26 of file Connectivity.h.
Constructor & Destructor Documentation
Connectivity::Connectivity (float aSizeNn)
Does nothing
Parameters
Integer indicated size of nearest neighbor list
Definition at line 10 of file Connectivity.cpp.
Member Function Documentation
double Connectivity::calculate (Partition & objPartition1, Partition & objPartition2) [virtual]
Does nothing
Implements ValidationIndex.
Definition at line 52 of file Connectivity.cpp.
double Connectivity::calculate (Partition * pAPartition, RelationSDN * pARelation, DataSet * pDataSet) [virtual]
Return value of connectivity from parameter partition
Parameters
Partition,RelationSDN and DataSet
Returns
Value connectivity
Implements ValidationIndex.
Definition at line 17 of file Connectivity.cpp.
References Partition::getLabelClusterOf(), NnList::getNnList(), RelationSDN::getNnList(), DataSet::getNumberOfObjects(), and DataSet::getVElements().
The documentation for this class was generated from the following files:
ValidationIndex/Connectivity.h
ValidationIndex/Connectivity.cpp