Partition Class Reference
Responsible to manage the partition file into the memory.
#include <Partition.h>
Classes
class Cluster
Each element in the dataset is allocated in one cluster.
Public Member Functions
Partition (string sAPathPartition, string sANamePartition)
void calculateCentroid (DataSet *pAObjDataSet)
void loadPartition ()
void generateRandomPartition (DataSet *pAObjDataSet)
void generatePartitionGroupCluster (DataSet *pAObjDataSet)
void printClusterLabels ()
void printClusters ()
void showCentroids ()
void writePartition ()
Cluster & getCluster (int iAPos)
int getNumClusters ()
int getNumObjects ()
map< string, int > getMObjects ()
vector< Partition::Cluster > getVObjects ()
int getLabelClusterOf (string sAObject)
vector< Partition::Cluster > getVectorObjCluster ()
vector< string > getObjectsInCluster (int ClusterLabel)
vector< double > getCentroidInCluster (int ClusterLabel)
Detailed Description
Responsible to manage the partition file into the memory.
Author
Valter Henrique, Vinicius Lopes, Gustavo Henrique, Katti Facelli
Since
09/02/10
Version
2.0 Colocar um comentário mais detalhado na classe dataset
Definition at line 26 of file Partition.h.
Constructor & Destructor Documentation
Partition::Partition (string sAPathPartition, string sANamePartition)
Does nothing
Parameters
Don't have any parameter
Definition at line 10 of file Partition.cpp.
References loadPartition().
Member Function Documentation
void Partition::calculateCentroid (DataSet * pAObjDataSet)
Calculate the centroid of the cluster
Parameters
Don't have
See also
calculateCentroid(DataSet &obADataSet)
Definition at line 18 of file Partition.cpp.
void Partition::generatePartitionGroupCluster (DataSet * pAObjDataSet)
Generates a random partition, grouping the objects in the same cluster,receiving as parameter a point to the object of the dataset
Parameters
*obADataSet
Returns
Don't have
Definition at line 227 of file Partition.cpp.
void Partition::generateRandomPartition (DataSet * pAObjDataSet)
Generates a random partition, receiving as parameter a point to the object of the dataset
Parameters
*obADataSet
Returns
Don't have
Definition at line 174 of file Partition.cpp.
References DataSet::getNumberOfObjects().
vector< double > Partition::getCentroidInCluster (int ClusterLabel)
Returns the centroid of Cluster
Parameters
Cluster Label
Returns
vector<double>
Definition at line 27 of file Partition.cpp.
Referenced by Deviation::calculate().
Partition::Cluster & Partition::getCluster (int iAPos)
Returns a specific cluster passing as argument the position where he is allocated
Parameters
int iPos
Definition at line 153 of file Partition.cpp.
Referenced by CRIndex::calculate().
int Partition::getLabelClusterOf (string sAObject)
Returns the cluster's label of parameter sObject
Parameters
sObject indicated the object label
Returns
Cluster's label
Definition at line 35 of file Partition.cpp.
Referenced by Connectivity::calculate().
map< string, int > Partition::getMObjects ()
Returns mObjects
Parameters
Don't have
Returns
map<string, int> mObjects
Definition at line 165 of file Partition.cpp.
int Partition::getNumClusters ()
Returns the number of cluster existing cluster on the partition, loaded in the loadPartition()
Parameters
Don't have
Returns
iNumClusters
See also
loadPartition(fs::path pathAPartition), iNumClusters
Definition at line 157 of file Partition.cpp.
Referenced by CRIndex::calculate().
int Partition::getNumObjects ()
Returns the number of existing objects on the partition, loaded in the loadPartition()
Parameters
Don't have
See also
loadPartition(fs::path pathAPartition)
Definition at line 161 of file Partition.cpp.
Referenced by CRIndex::calculate().
vector< string > Partition::getObjectsInCluster (int ClusterLabel)
Returns the rotule objects in ClusterLabel
Parameters
Cluster Label
Returns
vector<string>
Definition at line 23 of file Partition.cpp.
Referenced by Silhouette::calculate(), and Deviation::calculate().
vector< Partition::Cluster > Partition::getVectorObjCluster ()
Returns the vector all clusters of partition
Parameters
Don't have
Returns
vector<Cluster>
Definition at line 31 of file Partition.cpp.
Referenced by Silhouette::calculate(), and Deviation::calculate().
vector< Partition::Cluster > Partition::getVObjects ()
Returns vectorObjects, that contains objects of cluster type
Parameters
Don't have
Returns
vector<Cluster> vObCluster
Definition at line 169 of file Partition.cpp.
void Partition::loadPartition ()
charge to the partition in the memory, passing in the argument the path to load the partition in memory, passing as argument the path to the partition
Parameters
pathAPartition
Returns
Don't have.
Definition at line 53 of file Partition.cpp.
Referenced by Partition().
void Partition::printClusterLabels ()
Print the labels of the partition
Definition at line 283 of file Partition.cpp.
void Partition::writePartition ()
write the partition in disk, passing in the argument the path where the user want to save
Parameters
pathSaveIn
Returns
Don't have.
Definition at line 116 of file Partition.cpp.
The documentation for this class was generated from the following files:
Partition.h
Partition.cpp