CRIndex Class Reference
Public Member Functions
virtual double calculate (Partition &objPartition1, Partition &objPartition2)
virtual double calculate (Partition *pPartition, RelationSDN *pRelation, DataSet *pDataset)
Detailed Description
Definition at line 19 of file CRIndex.h.
Member Function Documentation
double CRIndex::calculate (Partition * pAPartition, RelationSDN * pARelation, DataSet * pDataSet) [virtual]
Method virtual from return value of measure validation internal
Parameters
Partition,RelationSDN and DataSet
Returns
Value from measure validation
Implements ValidationIndex.
Definition at line 87 of file CRIndex.cpp.
double CRIndex::calculate (Partition & objPartition1, Partition & objPartition2) [virtual]
Method virtual from return value of measure validation external
Parameters
Partition
Returns
Value from measure validation
Implements ValidationIndex.
Definition at line 11 of file CRIndex.cpp.
References Partition::getCluster(), Partition::getNumClusters(), and Partition::getNumObjects().
The documentation for this class was generated from the following files:
ValidationIndex/CRIndex.h
ValidationIndex/CRIndex.cpp