Similarity Class Reference
Responsible by management the measures of similarity.
#include <Similarity.h>Inheritance diagram for Similarity::
Public Member Functions
virtual double calculate (const vector< double > &vectorPattern_1, const vector< double > &vectorPattern_2)=0
Detailed Description
Responsible by management the measures of similarity.
Author
Valter Henrique
Since
01/02/10
Version
2.0 Responsible by management the measures of similarity, for example: Eucleadean Distance and Correlation Pearson
Definition at line 25 of file Similarity.h.
Member Function Documentation
virtual double Similarity::calculate (const vector< double > & vectorPattern_1, const vector< double > & vectorPattern_2) [pure virtual]
Each similarity class has the method 'calculate' that calculates the measures of similarity especific to that purpose
Implemented in Euclidean, and Pearson.
Referenced by Silhouette::calculate(), Deviation::calculate(), and DataSet::generateMatrix().
The documentation for this class was generated from the following files:
Similarity.h
Similarity.cpp