.TH "Connectivity" 3 "27 Jul 2010" "Version version2.0" "MOCLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Connectivity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Connectivity.h>\fP
.PP
Inherits \fBValidationIndex\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectivity\fP (float aSizeNn)"
.br
.ti -1c
.RI "virtual double \fBcalculate\fP (\fBPartition\fP *pAPartition, \fBRelationSDN\fP *pARelation, \fBDataSet\fP *pDataSet)"
.br
.ti -1c
.RI "virtual double \fBcalculate\fP (\fBPartition\fP &objPartition1, \fBPartition\fP &objPartition2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Gustavo Rodrigues 
.RE
.PP
\fBSince:\fP
.RS 4
12/03/10 
.RE
.PP
\fBVersion:\fP
.RS 4
2.0 
.RE
.PP

.PP
Definition at line 26 of file Connectivity.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Connectivity::Connectivity (float aSizeNn)"Does nothing 
.PP
\fBParameters:\fP
.RS 4
\fIInteger\fP indicated size of nearest neighbor list 
.RE
.PP

.PP
Definition at line 10 of file Connectivity.cpp.
.SH "Member Function Documentation"
.PP 
.SS "double Connectivity::calculate (\fBPartition\fP & objPartition1, \fBPartition\fP & objPartition2)\fC [virtual]\fP"Does nothing 
.PP
Implements \fBValidationIndex\fP.
.PP
Definition at line 52 of file Connectivity.cpp.
.SS "double Connectivity::calculate (\fBPartition\fP * pAPartition, \fBRelationSDN\fP * pARelation, \fBDataSet\fP * pDataSet)\fC [virtual]\fP"Return value of connectivity from parameter partition 
.PP
\fBParameters:\fP
.RS 4
\fI\fBPartition\fP,\fBRelationSDN\fP\fP and \fBDataSet\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Value connectivity 
.RE
.PP

.PP
Implements \fBValidationIndex\fP.
.PP
Definition at line 17 of file Connectivity.cpp.
.PP
References Partition::getLabelClusterOf(), NnList::getNnList(), RelationSDN::getNnList(), DataSet::getNumberOfObjects(), and DataSet::getVElements().

.SH "Author"
.PP 
Generated automatically by Doxygen for MOCLE from the source code.
