.TH "Deviation" 3 "27 Jul 2010" "Version version2.0" "MOCLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Deviation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Deviation.h>\fP
.PP
Inherits \fBValidationIndex\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeviation\fP ()"
.br
.ti -1c
.RI "virtual double \fBcalculate\fP (\fBPartition\fP *pAPartition, \fBRelationSDN\fP *pARelation, \fBDataSet\fP *pDataSet)"
.br
.ti -1c
.RI "virtual double \fBcalculate\fP (\fBPartition\fP &objPartition1, \fBPartition\fP &objPartition2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Gustavo Rodrigues 
.RE
.PP
\fBSince:\fP
.RS 4
12/03/10 
.RE
.PP
\fBVersion:\fP
.RS 4
2.0 
.RE
.PP

.PP
Definition at line 25 of file Deviation.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Deviation::Deviation ()"Does nothing 
.PP
\fBParameters:\fP
.RS 4
\fIDon't\fP have any parameter 
.RE
.PP

.PP
Definition at line 11 of file Deviation.cpp.
.SH "Member Function Documentation"
.PP 
.SS "double Deviation::calculate (\fBPartition\fP & objPartition1, \fBPartition\fP & objPartition2)\fC [virtual]\fP"Does nothing 
.PP
Implements \fBValidationIndex\fP.
.PP
Definition at line 40 of file Deviation.cpp.
.SS "double Deviation::calculate (\fBPartition\fP * pAPartition, \fBRelationSDN\fP * pARelation, \fBDataSet\fP * pDataSet)\fC [virtual]\fP"Return value of deviation from parameter partition 
.PP
\fBParameters:\fP
.RS 4
\fI\fBPartition\fP,\fBRelationSDN\fP\fP and \fBDataSet\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Value deviation 
.RE
.PP

.PP
calculate the summed distances for each pattern of a cluster 
.PP
Implements \fBValidationIndex\fP.
.PP
Definition at line 15 of file Deviation.cpp.
.PP
References Similarity::calculate(), Partition::getCentroidInCluster(), DataSet::getMapVector(), Partition::getObjectsInCluster(), RelationSDN::getSimilarity(), and Partition::getVectorObjCluster().

.SH "Author"
.PP 
Generated automatically by Doxygen for MOCLE from the source code.
