.TH "Exception" 3 "27 Jul 2010" "Version version2.0" "MOCLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exception \- 
.PP
\fBException\fP class throwed by the calculate method with one parameter of VI, NMI and CR classes.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exception.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBException\fP ()"
.br
.ti -1c
.RI "void \fBshowError\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBException\fP class throwed by the calculate method with one parameter of VI, NMI and CR classes. 

\fBAuthor:\fP
.RS 4
Vinicius Lopes 
.RE
.PP
\fBSince:\fP
.RS 4
27/02/10 
.RE
.PP
\fBVersion:\fP
.RS 4
1.0 All the exception that occured in MOCLE is gonna be treated in this class 
.RE
.PP

.PP
Definition at line 23 of file Exception.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Exception::Exception ()"Does nothing 
.PP
Definition at line 13 of file Exception.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void Exception::showError ()"Calculate the distance euclidean 
.PP
\fBReturns:\fP
.RS 4
the distance euclidean beween the dois pattern passed to the method 
.RE
.PP

.PP
Definition at line 15 of file Exception.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for MOCLE from the source code.
