.TH "InformationTheory" 3 "27 Jul 2010" "Version version2.0" "MOCLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InformationTheory \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InformationTheory.h>\fP
.PP
Inherited by \fBNMIIndex\fP, and \fBVIIndex\fP.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "double \fBenthropy\fP (\fBPartition\fP &objPartition)"
.br
.ti -1c
.RI "double \fBmutualInformation\fP (\fBPartition\fP &objPartition1, \fBPartition\fP &objPartition2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Vinicius 
.RE
.PP
\fBSince:\fP
.RS 4
??/\\?? 
.RE
.PP
\fBVersion:\fP
.RS 4
2.0 
.RE
.PP

.PP
Definition at line 16 of file InformationTheory.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for MOCLE from the source code.
