.TH "NMIIndex" 3 "27 Jul 2010" "Version version2.0" "MOCLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMIIndex \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBInformationTheory\fP, and \fBValidationIndex\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual double \fBcalculate\fP (\fBPartition\fP &objPartition1, \fBPartition\fP &objPartition2)"
.br
.ti -1c
.RI "virtual double \fBcalculate\fP (\fBPartition\fP *pPartition, \fBRelationSDN\fP *pRelation, \fBDataSet\fP *pDataset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file NMIIndex.h.
.SH "Member Function Documentation"
.PP 
.SS "double NMIIndex::calculate (\fBPartition\fP * pAPartition, \fBRelationSDN\fP * pARelation, \fBDataSet\fP * pDataSet)\fC [virtual]\fP"Method virtual from return value of measure validation internal 
.PP
\fBParameters:\fP
.RS 4
\fI\fBPartition\fP,\fBRelationSDN\fP\fP and \fBDataSet\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Value from measure validation 
.RE
.PP

.PP
Implements \fBValidationIndex\fP.
.PP
Definition at line 20 of file NMIIndex.cpp.
.SS "double NMIIndex::calculate (\fBPartition\fP & objPartition1, \fBPartition\fP & objPartition2)\fC [virtual]\fP"Method virtual from return value of measure validation external 
.PP
\fBParameters:\fP
.RS 4
\fI\fBPartition\fP\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Value from measure validation 
.RE
.PP

.PP
Implements \fBValidationIndex\fP.
.PP
Definition at line 11 of file NMIIndex.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for MOCLE from the source code.
