.TH "NnList" 3 "27 Jul 2010" "Version version2.0" "MOCLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NnList \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NnList.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNnList\fP ()"
.br
.ti -1c
.RI "void \fBsetNnList\fP (map< string, map< string, double > > mapAObMap)"
.br
.ti -1c
.RI "vector< pair< string, vector< string > > > \fBgetNnList\fP ()"
.br
.ti -1c
.RI "vector< string > \fBgetNnList\fP (string sRotuloObject)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Gustavo Rodrigues 
.RE
.PP
\fBSince:\fP
.RS 4
12/03/10 
.RE
.PP
\fBVersion:\fP
.RS 4
2.0 This class stores the nearest neighbors of all objects in the dataset according to similarity and distance matrix of similarity 
.RE
.PP

.PP
Definition at line 26 of file NnList.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NnList::NnList ()"Does nothing 
.PP
\fBParameters:\fP
.RS 4
\fIDon't\fP have any parameter 
.RE
.PP

.PP
Definition at line 10 of file NnList.cpp.
.SH "Member Function Documentation"
.PP 
.SS "vector< string > NnList::getNnList (string sRotuloObject)"Return the nearest neighbor list of object sRotuloOBject 
.PP
\fBParameters:\fP
.RS 4
\fIRotulo\fP of object 
.RE
.PP
\fBReturns:\fP
.RS 4
Nearest neighbor list 
.RE
.PP

.PP
Definition at line 54 of file NnList.cpp.
.SS "vector< pair< string, vector< string > > > NnList::getNnList ()"Return the nearest neighbor list 
.PP
\fBParameters:\fP
.RS 4
\fIDon't\fP have 
.RE
.PP
\fBReturns:\fP
.RS 4
Nearest neighbor list 
.RE
.PP

.PP
Definition at line 18 of file NnList.cpp.
.PP
Referenced by Connectivity::calculate().
.SS "void NnList::setNnList (map< string, map< string, double > > mapAObMap)"Set entire nearest neighbor list from dataset 
.PP
\fBParameters:\fP
.RS 4
\fIMatrix\fP map 
.RE
.PP
\fBReturns:\fP
.RS 4
Don't have 
.RE
.PP

.PP
Definition at line 22 of file NnList.cpp.
.PP
Referenced by RelationSDN::setNnList().

.SH "Author"
.PP 
Generated automatically by Doxygen for MOCLE from the source code.
