.TH "Partition" 3 "27 Jul 2010" "Version version2.0" "MOCLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Partition \- 
.PP
Responsible to manage the partition file into the memory.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Partition.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCluster\fP"
.br
.RI "\fIEach element in the dataset is allocated in one cluster. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartition\fP (string sAPathPartition, string sANamePartition)"
.br
.ti -1c
.RI "void \fBcalculateCentroid\fP (\fBDataSet\fP *pAObjDataSet)"
.br
.ti -1c
.RI "void \fBloadPartition\fP ()"
.br
.ti -1c
.RI "void \fBgenerateRandomPartition\fP (\fBDataSet\fP *pAObjDataSet)"
.br
.ti -1c
.RI "void \fBgeneratePartitionGroupCluster\fP (\fBDataSet\fP *pAObjDataSet)"
.br
.ti -1c
.RI "void \fBprintClusterLabels\fP ()"
.br
.ti -1c
.RI "void \fBprintClusters\fP ()"
.br
.ti -1c
.RI "void \fBshowCentroids\fP ()"
.br
.ti -1c
.RI "void \fBwritePartition\fP ()"
.br
.ti -1c
.RI "Cluster & \fBgetCluster\fP (int iAPos)"
.br
.ti -1c
.RI "int \fBgetNumClusters\fP ()"
.br
.ti -1c
.RI "int \fBgetNumObjects\fP ()"
.br
.ti -1c
.RI "map< string, int > \fBgetMObjects\fP ()"
.br
.ti -1c
.RI "vector< Partition::Cluster > \fBgetVObjects\fP ()"
.br
.ti -1c
.RI "int \fBgetLabelClusterOf\fP (string sAObject)"
.br
.ti -1c
.RI "vector< Partition::Cluster > \fBgetVectorObjCluster\fP ()"
.br
.ti -1c
.RI "vector< string > \fBgetObjectsInCluster\fP (int ClusterLabel)"
.br
.ti -1c
.RI "vector< double > \fBgetCentroidInCluster\fP (int ClusterLabel)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Responsible to manage the partition file into the memory. 

\fBAuthor:\fP
.RS 4
Valter Henrique, Vinicius Lopes, Gustavo Henrique, Katti Facelli 
.RE
.PP
\fBSince:\fP
.RS 4
09/02/10 
.RE
.PP
\fBVersion:\fP
.RS 4
2.0 Colocar um comentário mais detalhado na classe dataset 
.RE
.PP

.PP
Definition at line 26 of file Partition.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Partition::Partition (string sAPathPartition, string sANamePartition)"Does nothing 
.PP
\fBParameters:\fP
.RS 4
\fIDon't\fP have any parameter 
.RE
.PP

.PP
Definition at line 10 of file Partition.cpp.
.PP
References loadPartition().
.SH "Member Function Documentation"
.PP 
.SS "void Partition::calculateCentroid (\fBDataSet\fP * pAObjDataSet)"Calculate the centroid of the cluster 
.PP
\fBParameters:\fP
.RS 4
\fIDon't\fP have 
.RE
.PP
\fBSee also:\fP
.RS 4
calculateCentroid(DataSet &obADataSet) 
.RE
.PP

.PP
Definition at line 18 of file Partition.cpp.
.SS "void Partition::generatePartitionGroupCluster (\fBDataSet\fP * pAObjDataSet)"Generates a random partition, grouping the objects in the same cluster,receiving as parameter a point to the object of the dataset 
.PP
\fBParameters:\fP
.RS 4
\fI*obADataSet\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Don't have 
.RE
.PP

.PP
Definition at line 227 of file Partition.cpp.
.SS "void Partition::generateRandomPartition (\fBDataSet\fP * pAObjDataSet)"Generates a random partition, receiving as parameter a point to the object of the dataset 
.PP
\fBParameters:\fP
.RS 4
\fI*obADataSet\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Don't have 
.RE
.PP

.PP
Definition at line 174 of file Partition.cpp.
.PP
References DataSet::getNumberOfObjects().
.SS "vector< double > Partition::getCentroidInCluster (int ClusterLabel)"Returns the centroid of Cluster 
.PP
\fBParameters:\fP
.RS 4
\fICluster\fP Label 
.RE
.PP
\fBReturns:\fP
.RS 4
vector<double> 
.RE
.PP

.PP
Definition at line 27 of file Partition.cpp.
.PP
Referenced by Deviation::calculate().
.SS "Partition::Cluster & Partition::getCluster (int iAPos)"Returns a specific cluster passing as argument the position where he is allocated 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP iPos 
.RE
.PP

.PP
Definition at line 153 of file Partition.cpp.
.PP
Referenced by CRIndex::calculate().
.SS "int Partition::getLabelClusterOf (string sAObject)"Returns the cluster's label of parameter sObject 
.PP
\fBParameters:\fP
.RS 4
\fIsObject\fP indicated the object label 
.RE
.PP
\fBReturns:\fP
.RS 4
Cluster's label 
.RE
.PP

.PP
Definition at line 35 of file Partition.cpp.
.PP
Referenced by Connectivity::calculate().
.SS "map< string, int > Partition::getMObjects ()"Returns mObjects 
.PP
\fBParameters:\fP
.RS 4
\fIDon't\fP have 
.RE
.PP
\fBReturns:\fP
.RS 4
map<string, int> mObjects 
.RE
.PP

.PP
Definition at line 165 of file Partition.cpp.
.SS "int Partition::getNumClusters ()"Returns the number of cluster existing cluster on the partition, loaded in the \fBloadPartition()\fP 
.PP
\fBParameters:\fP
.RS 4
\fIDon't\fP have 
.RE
.PP
\fBReturns:\fP
.RS 4
iNumClusters 
.RE
.PP
\fBSee also:\fP
.RS 4
loadPartition(fs::path pathAPartition), iNumClusters 
.RE
.PP

.PP
Definition at line 157 of file Partition.cpp.
.PP
Referenced by CRIndex::calculate().
.SS "int Partition::getNumObjects ()"Returns the number of existing objects on the partition, loaded in the \fBloadPartition()\fP 
.PP
\fBParameters:\fP
.RS 4
\fIDon't\fP have 
.RE
.PP
\fBSee also:\fP
.RS 4
loadPartition(fs::path pathAPartition) 
.RE
.PP

.PP
Definition at line 161 of file Partition.cpp.
.PP
Referenced by CRIndex::calculate().
.SS "vector< string > Partition::getObjectsInCluster (int ClusterLabel)"Returns the rotule objects in ClusterLabel 
.PP
\fBParameters:\fP
.RS 4
\fICluster\fP Label 
.RE
.PP
\fBReturns:\fP
.RS 4
vector<string> 
.RE
.PP

.PP
Definition at line 23 of file Partition.cpp.
.PP
Referenced by Silhouette::calculate(), and Deviation::calculate().
.SS "vector< Partition::Cluster > Partition::getVectorObjCluster ()"Returns the vector all clusters of partition 
.PP
\fBParameters:\fP
.RS 4
\fIDon't\fP have 
.RE
.PP
\fBReturns:\fP
.RS 4
vector<Cluster> 
.RE
.PP

.PP
Definition at line 31 of file Partition.cpp.
.PP
Referenced by Silhouette::calculate(), and Deviation::calculate().
.SS "vector< Partition::Cluster > Partition::getVObjects ()"Returns vectorObjects, that contains objects of cluster type 
.PP
\fBParameters:\fP
.RS 4
\fIDon't\fP have 
.RE
.PP
\fBReturns:\fP
.RS 4
vector<Cluster> vObCluster 
.RE
.PP

.PP
Definition at line 169 of file Partition.cpp.
.SS "void Partition::loadPartition ()"charge to the partition in the memory, passing in the argument the path to load the partition in memory, passing as argument the path to the partition 
.PP
\fBParameters:\fP
.RS 4
\fIpathAPartition\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Don't have. 
.RE
.PP

.PP
Definition at line 53 of file Partition.cpp.
.PP
Referenced by Partition().
.SS "void Partition::printClusterLabels ()"Print the labels of the partition 
.PP
Definition at line 283 of file Partition.cpp.
.SS "void Partition::writePartition ()"write the partition in disk, passing in the argument the path where the user want to save 
.PP
\fBParameters:\fP
.RS 4
\fIpathSaveIn\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Don't have. 
.RE
.PP

.PP
Definition at line 116 of file Partition.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for MOCLE from the source code.
