.TH "Pearson" 3 "27 Jul 2010" "Version version2.0" "MOCLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pearson \- 
.PP
Responsible to calculate the pearson correlation coefficient.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Pearson.h>\fP
.PP
Inherits \fBSimilarity\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBcalculate\fP (const vector< double > &vectorPattern_1, const vector< double > &vectorPattern_2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Responsible to calculate the pearson correlation coefficient. 

Responsible to calculate the pearson correlation coefficient, this is made in calculate method 
.PP
Definition at line 15 of file Pearson.h.
.SH "Member Function Documentation"
.PP 
.SS "double Pearson::calculate (const vector< double > & vectorPattern_1, const vector< double > & vectorPattern_2)\fC [virtual]\fP"Calculate the pearson correlation coefficient. 
.PP
\fBReturns:\fP
.RS 4
the pearson correlation coefficient 
.RE
.PP

.PP
Implements \fBSimilarity\fP.
.PP
Definition at line 18 of file Pearson.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for MOCLE from the source code.
