.TH "Silhouette" 3 "27 Jul 2010" "Version version2.0" "MOCLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Silhouette \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Silhouette.h>\fP
.PP
Inherits \fBValidationIndex\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual double \fBcalculate\fP (\fBPartition\fP *pAPartition, \fBRelationSDN\fP *pARelation, \fBDataSet\fP *pADataset)"
.br
.ti -1c
.RI "virtual double \fBcalculate\fP (\fBPartition\fP &objPartition1, \fBPartition\fP &objPartition2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Gustavo Rodrigues 
.RE
.PP
\fBSince:\fP
.RS 4
22/03/10 
.RE
.PP
\fBVersion:\fP
.RS 4
2.0 
.RE
.PP

.PP
Definition at line 22 of file Silhouette.h.
.SH "Member Function Documentation"
.PP 
.SS "double Silhouette::calculate (\fBPartition\fP & objPartition1, \fBPartition\fP & objPartition2)\fC [virtual]\fP"Does nothing 
.PP
Implements \fBValidationIndex\fP.
.PP
Definition at line 205 of file Silhouette.cpp.
.SS "double Silhouette::calculate (\fBPartition\fP * pAPartition, \fBRelationSDN\fP * pARelation, \fBDataSet\fP * pADataset)\fC [virtual]\fP"Return value of silhouette from parameter partition 
.PP
\fBParameters:\fP
.RS 4
\fI\fBPartition\fP,\fBRelationSDN\fP\fP and \fBDataSet\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Value silhouette 
.RE
.PP

.PP
Implements \fBValidationIndex\fP.
.PP
Definition at line 18 of file Silhouette.cpp.
.PP
References Similarity::calculate(), DataSet::getMapVector(), Partition::getObjectsInCluster(), RelationSDN::getSimilarity(), and Partition::getVectorObjCluster().

.SH "Author"
.PP 
Generated automatically by Doxygen for MOCLE from the source code.
