.TH "Similarity" 3 "27 Jul 2010" "Version version2.0" "MOCLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Similarity \- 
.PP
Responsible by management the measures of similarity.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Similarity.h>\fP
.PP
Inherited by \fBEuclidean\fP, and \fBPearson\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual double \fBcalculate\fP (const vector< double > &vectorPattern_1, const vector< double > &vectorPattern_2)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Responsible by management the measures of similarity. 

\fBAuthor:\fP
.RS 4
Valter Henrique 
.RE
.PP
\fBSince:\fP
.RS 4
01/02/10 
.RE
.PP
\fBVersion:\fP
.RS 4
2.0 Responsible by management the measures of similarity, for example: Eucleadean Distance and Correlation \fBPearson\fP 
.RE
.PP

.PP
Definition at line 25 of file Similarity.h.
.SH "Member Function Documentation"
.PP 
.SS "virtual double Similarity::calculate (const vector< double > & vectorPattern_1, const vector< double > & vectorPattern_2)\fC [pure virtual]\fP"Each similarity class has the method 'calculate' that calculates the measures of similarity especific to that purpose 
.PP
Implemented in \fBEuclidean\fP, and \fBPearson\fP.
.PP
Referenced by Silhouette::calculate(), Deviation::calculate(), and DataSet::generateMatrix().

.SH "Author"
.PP 
Generated automatically by Doxygen for MOCLE from the source code.
